### ISSUE TITLE
Investigate max datagram size

### ISSUE THREAD

**Issue by danielballan** [NSLS-II/caproto#262]
From `test_many_connections_same_ioc[INFO-threading-connections:{}-500]`:

```
Exception in thread retry:
Traceback (most recent call last):
  File "/Users/dallan/miniconda3/envs/dd/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/Users/dallan/miniconda3/envs/dd/lib/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/dallan/Documents/Repos/caproto/caproto/threading/client.py", line 612, in _retry_unanswered_searches
    self.send(ca.EPICS_CA1_PORT, ca.VersionRequest(0, 13), *batch)
  File "/Users/dallan/Documents/Repos/caproto/caproto/threading/client.py", line 434, in send
    self.udp_sock.sendto(bytes_to_send, (host, port))
OSError: [Errno 40] Message too long
```

**Comment by danielballan** [comment]
@klauer Do you think we can close this in light of #369?

**Comment by klauer** [comment]
Depends on if we want to attempt determining the maximum dynamically on all platforms. Maybe close this and open another stating as much?
